'use client';
import {useHydrated} from '@/hooks/use-hydrated';
import {useMemo,useState} from 'react';import Link from 'next/link';import {ArrowUpRight,Search,SlidersHorizontal,ArrowRight} from 'lucide-react';import type {Catalog} from '@/lib/catalog/types';import {formatInr} from '@/lib/catalog/query';import {Boutique} from './boutique/boutique';import {ScentArt} from './scent-art';
export function CollectionExplorer({catalog}: {catalog:Catalog}){
 const hydrated=useHydrated();const [search,setSearch]=useState(''),[family,setFamily]=useState('All scents'),[budget,setBudget]=useState(''),[selectedId,setSelected]=useState('liquid-brun');
 const items=useMemo(()=>catalog.fragrances.filter(f=>(f.name+' '+f.brand+' '+Object.keys(f.profile.traits).join(' ')).toLowerCase().includes(search.toLowerCase())&&(family==='All scents'||f.profile.family===family)&&(!budget||(f.referencePrice.kind==='reference'&&f.referencePrice.amountInr<=Number(budget)))),[catalog,search,family,budget]);
 const selected=items.find(f=>f.id===selectedId)??items[0];const families=['All scents',...new Set(catalog.fragrances.map(f=>f.profile.family))];
 return <main id="main" className="page collection-page"><div className="collection-heading"><div><p className="eyebrow">AN INDEPENDENT GUIDE TO FINDING YOUR SCENT</p><h1>Good scents.<br/><em>Better decisions.</em></h1></div><div className="intro-side"><p>Step into a collection of 15 fragrances.<br/>Explore the feeling, understand the facts,<br/>and find what fits <em>you.</em></p><Link className="text-link" href="/discover">Find my scent <ArrowUpRight size={19}/></Link></div></div>
 <div className="browse-toolbar"><label className="search-field"><Search size={18}/><input disabled={!hydrated} aria-label="Search fragrances" placeholder="Search a scent, brand or note…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="budget-filter"><SlidersHorizontal size={17}/><select disabled={!hydrated} aria-label="Reference budget" value={budget} onChange={e=>setBudget(e.target.value)}><option value="">Any reference budget</option><option value="2000">Up to ₹2,000 reference</option><option value="3500">Up to ₹3,500 reference</option><option value="6000">Up to ₹6,000 reference</option></select></label><span className="result-count">{items.length} scents to explore</span></div>
 <div className="family-tabs" aria-label="Scent families">{families.map(x=><button type="button" key={x} aria-pressed={family===x} onClick={()=>setFamily(x)}>{x}</button>)}</div>
 {selected?<div className="gallery-layout"><Boutique items={items} selectedId={selected.id} onSelect={setSelected}/><section className="selected-panel" data-testid="selected-fragrance"><div className="panel-number">{String(catalog.fragrances.indexOf(selected)+1).padStart(2,'0')} / 15 <span>IN FOCUS</span></div><p className="eyebrow brand">{selected.brand}</p><h2>{selected.name}</h2><span className="family-label">{selected.profile.family}</span><p className="summary">{selected.summary}</p><div className="note-pills">{Object.entries(selected.profile.traits).filter(([,v])=>(v??0)>=3).slice(0,3).map(([t])=><span key={t}>{t}</span>)}</div><div className="price-line"><strong>{selected.referencePrice.kind==='reference'?formatInr(selected.referencePrice.amountInr):'Price unconfirmed'}</strong><span>{selected.referencePrice.kind==='reference'?'User reference · not a live offer':'Check exact variant with seller'}</span></div><Link href={'/perfumes/'+selected.slug} className="button">Explore this scent <ArrowRight size={18}/></Link></section></div>:<section className="empty-state"><h2>No scents found</h2><p>Try a different name, family or reference budget.</p><button className="button" onClick={()=>{setSearch('');setFamily('All scents');setBudget('');}}>Clear filters</button></section>}
 <div className="section-heading"><div><p className="eyebrow">YOUR NEXT DISCOVERY</p><h2>The collection</h2></div><span>Notes are impressions. Sampling is the real test.</span></div><div className="collection-grid">{items.map((f,i)=><article className={'fragrance-card '+(f.id===selected?.id?'is-selected':'')} key={f.id}><button type="button" className="card-explore" aria-label={'Explore '+f.name} aria-pressed={f.id===selected?.id} onClick={()=>setSelected(f.id)}><div className="card-art"><span>{String(i+1).padStart(2,'0')}</span><ScentArt color={f.profile.color} small/><ArrowUpRight size={20}/></div><div className="card-info"><p className="eyebrow">{f.brand}</p><h3>{f.name}</h3><p>{f.profile.family}</p><div className="card-price">{f.referencePrice.kind==='reference'?formatInr(f.referencePrice.amountInr)+' reference':'Price unconfirmed'}<span>→</span></div></div></button><Link className="card-profile" href={'/perfumes/'+f.slug}>View profile <ArrowUpRight size={14}/></Link></article>)}</div><aside className="guide-callout"><span className="large-star">✳</span><div><h2>Your skin. Your weather. Your scent.</h2><p>A note pyramid can help you imagine a perfume. It can’t tell you how it will wear on you. We show our sources, flag uncertainty and encourage you to sample first.</p></div><Link href="/discover" className="button secondary">Build my shortlist <ArrowUpRight size={18}/></Link></aside></main>;
}
